/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "landing-sand": "#f3ede4",
        "landing-ink": "#141b2d",
        "landing-coral": "#e8542a",
        "landing-mist": "#e8edf5",
        "landing-void": "#070b14",
        "landing-night": "#0d1424",
        "landing-gold": "#f59e0b",
        background: "var(--md-background)",
        "surface-variant": "#e0e3e5",
        primary: "#004ac6",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#004c6e",
        "secondary-fixed": "#e2dfff",
        "inverse-on-surface": "#eff1f3",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "on-background": "var(--md-text)",
        "error-container": "#ffdad6",
        "secondary-container": "#645efb",
        "on-secondary-container": "#fffbff",
        "tertiary-container": "#0074a6",
        secondary: "#4b41e1",
        "secondary-fixed-dim": "#c3c0ff",
        "on-secondary-fixed-variant": "#3323cc",
        "on-primary-fixed": "#00174b",
        "on-surface": "var(--md-text)",
        "tertiary-fixed-dim": "#89ceff",
        "primary-container": "#2563eb",
        "surface-bright": "#f7f9fb",
        "on-error-container": "#93000a",
        "outline-variant": "var(--md-border)",
        "inverse-primary": "#b4c5ff",
        "on-error": "#ffffff",
        "inverse-surface": "#2d3133",
        outline: "var(--md-border-strong)",
        "surface-container-low": "var(--md-surface-muted)",
        "primary-fixed-dim": "#b4c5ff",
        "on-tertiary-fixed": "#001e2f",
        "surface-container-high": "var(--md-surface-subtle)",
        "surface-container": "var(--md-surface-subtle)",
        "on-surface-variant": "var(--md-text-muted)",
        "surface-container-lowest": "var(--md-surface-elevated)",
        "surface-tint": "#0053db",
        surface: "var(--md-surface)",
        "primary-fixed": "#dbe1ff",
        "on-tertiary": "#ffffff",
        tertiary: "#005a82",
        "on-secondary-fixed": "#0f0069",
        "surface-dim": "#d8dadc",
        error: "#ba1a1a",
        "on-tertiary-container": "#e4f2ff",
        "tertiary-fixed": "#c9e6ff",
        "on-primary-container": "#eeefff",
        "on-primary-fixed-variant": "#003ea8"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        gutter: "16px",
        xl: "28px",
        base: "4px",
        md: "12px",
        sm: "6px",
        lg: "16px",
        "container-max": "1280px",
      },
      fontFamily: {
        "landing-display": ["Syne", "Fraunces", "Georgia", "serif"],
        "landing-body": ["Plus Jakarta Sans", "DM Sans", "Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "mono-sm": ["Geist", "sans-serif"],
      },
      keyframes: {
        "landing-fade-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "landing-ticket-float": {
          "0%, 100%": { transform: "translateY(0) rotate(-1deg)" },
          "50%": { transform: "translateY(-8px) rotate(1deg)" },
        },
      },
      animation: {
        "landing-fade-up": "landing-fade-up 0.7s ease-out both",
        "landing-ticket-float": "landing-ticket-float 7s ease-in-out infinite",
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "18px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "mono-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
