/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#f7f9fb",
        "surface-variant": "#e0e3e5",
        primary: "#004ac6",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#004c6e",
        "secondary-fixed": "#e2dfff",
        "inverse-on-surface": "#eff1f3",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "on-background": "#191c1e",
        "error-container": "#ffdad6",
        "secondary-container": "#645efb",
        "on-secondary-container": "#fffbff",
        "tertiary-container": "#0074a6",
        secondary: "#4b41e1",
        "secondary-fixed-dim": "#c3c0ff",
        "on-secondary-fixed-variant": "#3323cc",
        "on-primary-fixed": "#00174b",
        "on-surface": "#191c1e",
        "tertiary-fixed-dim": "#89ceff",
        "primary-container": "#2563eb",
        "surface-bright": "#f7f9fb",
        "on-error-container": "#93000a",
        "outline-variant": "#c3c6d7",
        "inverse-primary": "#b4c5ff",
        "on-error": "#ffffff",
        "inverse-surface": "#2d3133",
        outline: "#737686",
        "surface-container-low": "#f2f4f6",
        "primary-fixed-dim": "#b4c5ff",
        "on-tertiary-fixed": "#001e2f",
        "surface-container-high": "#e6e8ea",
        "surface-container": "#eceef0",
        "on-surface-variant": "#434655",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#0053db",
        surface: "#f7f9fb",
        "primary-fixed": "#dbe1ff",
        "on-tertiary": "#ffffff",
        tertiary: "#005a82",
        "on-secondary-fixed": "#0f0069",
        "surface-dim": "#d8dadc",
        error: "#ba1a1a",
        "on-tertiary-container": "#e4f2ff",
        "tertiary-fixed": "#c9e6ff",
        "on-primary-container": "#eeefff",
        "on-primary-fixed-variant": "#003ea8"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        gutter: "16px",
        xl: "28px",
        base: "4px",
        md: "12px",
        sm: "6px",
        lg: "16px",
        "container-max": "1280px",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "mono-sm": ["Geist", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "18px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "mono-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
